# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-deps
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install -U tox coveralls

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - restore_cache:
          keys:
          - v1-tox-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-tox-

      - run:
          name: run-tests
          command: |
            . venv/bin/activate

            tox

      - store_test_results:
          path: test-reports

      - save_cache:
          paths:
            - ./.tox
          key: v1-tox-{{ checksum "setup.py" }}

      - run:
          name: coveralls
          command: |
            . venv/bin/activate

            [[ -z "$COVERALLS_REPO_TOKEN" ]] || coveralls

